import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Box, Container, CssBaseline, ThemeProvider } from "@mui/material";
import './styles/style.css'
import Header from "./components/Header";
import Footer from "./components/Footer";
import CopyrightBlock from "./components/CopyrightBlock";
import theme from "./theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
            <Container maxWidth={'xl'} sx={{pl: 0, pr: 0}}>
              <Box sx={{display: 'flex', flexDirection: 'column', justifyContent: 'space-between'}}>
                <ThemeProvider theme={theme}>
                    <CssBaseline />
                    <Header />
                    {children}
                    <footer>
                      <Footer />
                      <CopyrightBlock />
                    </footer>
                </ThemeProvider>
              </Box>
            </Container>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
